# Site settings
title: NANJIAN | 南健
email: contact@nanjian.com.sg
url: nanjian.com.sg
description: "Write an awesome description for your new site here. You can edit this line in _config.yml. It will appear in your document head meta (for Google search results) and in your feed.xml site description."
keywords: "company, board game, start-up"
skills: "NANJIAN, for a better life."
meta_author: LastName FirstName

# Google webmaster tools
google_verify:

# https://ssl.bing.com/webmaster/configure/verify/ownership Option 2 content= goes here
bing_verify:

# Contact form:
# - static : pass through formspree.io to validate email sending
# - disqus : replace contact form by disqus thread
# - comment the line below if you want to stick with the default PHP contact form
contact: static

# If you use disqus you need disqus shortname
# https://help.disqus.com/customer/portal/articles/466208
disqus_shortname: myshortname

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: D2A05A
  primary-rgb: "30,30,30" 
  secondary: 	 1E1E1E 
  secondary-dark: 1E1E1E   

# Footer settings
footer:
  copyright: NANJIAN
  location: Location
  #social: Around the Web
  credits: Credits

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
#
# Postal address (add as many lines as necessary)
address:
  - line: 03-19, 41 Holland Drive, Block 41, 
  - line: Singapore 270041

# Credits content
credits: 2013-2018 © NANJIAN 

# Build settings
markdown: kramdown
permalink: pretty
